### ISSUE TITLE
.NET Standard

### ISSUE THREAD

**Issue by savian-net** [MoaidHathot/Dumpify#11]
I am running .NET Framework 4.8. No choice due to VSTO not being upgraded by Microsoft. 

The package fails on nuget due to 'You are trying to install this package into a project that targets '.NETFramework,Version=v4.8', but the package does not contain any assembly references or content files that are compatible'. Not sure but this should compile to .NET Standard 2.0. 

I can download and compile myself. Thanks for introducing me to Spectre.Console. Did not know about that.

**Comment by Hejle** [comment]
Hi @savian-net. The issue of targeting .NET Standard 2.0 was recently solved in https://github.com/MoaidHathot/Dumpify/pull/7.
As @MoaidHathot said in #2, it will be probably released before the end of the month.

**Comment by MoaidHathot** [comment]
Hi @savian-net, as @Hejle has mentioned, the support for .NET Standard 2.0 was added very recently, thanks to @Hejle, but we still did not release the new version to Nuget.
I have one more feature to add to this release, and I'm planning on releasing the new Nuget version *tomorrow*'s night :)
In the meanwhile, you can clone the repo and build it yourself, there should be .NETStandard compatible outputs.

**Comment by MoaidHathot** [comment]
@savian-net, I wasn't able to release the version tonight as I'm still working on some features and further testings are needed.
Hoping to be able to do that in the next couple of days. In the meanwhile, you can clone the repo and build it to get the .NETStandard 2.0 support.

**Comment by savian-net** [comment]
No rush. All of us are slinging lots of code on any given day. I just appreciate that someone is working on it for the community.

**Comment by MoaidHathot** [comment]
@savian-net, I just released [v.0.6.0](https://github.com/MoaidHathot/Dumpify/releases/tag/0.6.0) that includes this change. Thanks @Hejle for the contribution.
