### ISSUE TITLE
Question: .NETStandard 2.0 support

### ISSUE THREAD

**Issue by sadedil** [MoaidHathot/Dumpify#2]
Greetings,

Is there any hard rule to keep .NET dependencies >= .NETStandard,Version=2.1.
Can this support Version=2.0 too?

**Comment by MoaidHathot** [comment]
Greetings,

There shouldn't be any hard rule for why not supporting NETStandard 2.0, but it require some code changes since some language features are not supported in NETStandard 2.0.
Nothing too hard to do, I will try to include it in the next release.

**Comment by BrightLight** [comment]
NETStandard 2.0 would allow to use the package also in full framework. Therefore if there's no hard dependency on Core, NETStandard 2.0 would be preferable.

**Comment by MoaidHathot** [comment]
@BrightLight, yeah, we should be able to support `NETStandard 2.0`. Hoping to do that with the new release I'm working on towards the end of this month.

**Comment by Hejle** [comment]
Hey Moaid,

I was just a bit interested in how to add .NET Standard 2.0 support and did it in the following branch:
https://github.com/Hejle/Dumpify/tree/feature/netstandard2.0_support

Just letting you know in case you want to take inspiration from it, however I am pretty sure its not a complete or good version - Looking at you DumpColor.cs

But yeah, if you already have it all solved you can just ignore this.

**Comment by MoaidHathot** [comment]
Hi @Hejle, thanks for this!
I will need to do some small adjustments, hoping to merge it this weekend.

**Comment by Hejle** [comment]
Looking forward to see the adjustments!

**Comment by MoaidHathot** [comment]
Hi @Hejle, I'm almost done. I did some modifications, but the result was inspired by your branch. 
Since you worked hard on this, do you want to be the one to marge the PR so that you can get contribution credits? :)
If it interest you, I'll share my branch, and you could create a PR from it (or copy it to your branch for the commits).

**Comment by MoaidHathot** [comment]
@sadedil, @BrightLight, the work on this feature is done, and it should be part of the next release, which is due this month. Thank you for suggesting it :)

@Hejle, the following is my branch. If you are interested in contribution (commit) credits, please say so and we will figure out a way. I'm planning to merge this branch into master during the weekend, but I can delay it if you need more time :)
Regardless of contribution credits, I will mention you in the Release Notes of the next version.
https://github.com/MoaidHathot/Dumpify/tree/feature/netstandard2.0

**Comment by Hejle** [comment]
That sounds great @MoaidHathot.
I will see if I can get it into my branch and make the PR, but if not, its not a big deal.
I will look at it today or tomorrow. :)

**Comment by MoaidHathot** [comment]
@BrightLight, @sadedil, @Hejle, the PR was merged into Main. I'll release the new version before end of month.
Thanks @Hejle for the contribution!   #7

**Comment by sadedil** [comment]
@MoaidHathot, @Hejle thank you both.
