### ISSUE TITLE
Virtual Member

### ISSUE THREAD

**Issue by yudielcurbelo** [MoaidHathot/Dumpify#20]
When using EF Core Lazy Loading `Dump()` will load the whole tree. 
Using `MaxDepth = 1` helps, but then you will see a lot of `[Exceeded max depth 1]` in the console. 
Is there a way to limit the library to ignore virtual members.

**Comment by MoaidHathot** [comment]
Hi @yudielcurbelo, interesting use case! 
Do you mean to ignore all members (also inherited) that is marked with the `virtual` keyboard? 
I'm not proficient enough with EF Core, is there another way to determine which members are currently "lazy" loaded? Will the compiler add some attributes to the members? I'm asking to determine whether there is a more precise way to filter lazy-loaded members in this context.

I can add configuration to ignore virtual members, it should be easy. I will look into it this weekend.

**Comment by Empiree** [comment]
> Hi @yudielcurbelo, interesting use case! Do you mean to ignore all members (also inherited) that is marked with the `virtual` keyboard? I'm not proficient enough with EF Core, is there another way to determine which members are currently "lazy" loaded? Will the compiler/EF-Core add some attributes to the members? I'm asking to determine whether there is a more precise way to filter lazy-loaded members in this context.
> 
> I can add configuration to ignore virtual members, it should be easy. I will look into it this weekend.

Hello, I really like your project, can I contribute and solve this problem? 

As far as I understand, we need to add IncludeVirtualMembers to MembersConfig and depending on this value output virtual members.

**Comment by MoaidHathot** [comment]
Hi @Empiree, thanks!
Basically, yeah. Most of the changes should be inside `MembersProvider`. I would love to get help :)

**Comment by Empiree** [comment]
> Hi @Empiree, thanks! Basically, yeah. Most of the changes should be inside `MemberProvider`. I would love to get help :)

It's done! If any changes are needed, I'll be happy to fix them :)

**Comment by MoaidHathot** [comment]
Thanks @Empiree and sorry for the delay in response. I'll review it tomorrow :)

**Comment by MoaidHathot** [comment]
Thanks @Empiree for your contribution, I've approved the PR. The change should be part of the next release, towards the end of March :)
