### ISSUE TITLE
dumpify nuget manager install error: NU1108: Cycle detected. 

### ISSUE THREAD

**Issue by hooseinsaid** [MoaidHathot/Dumpify#26]
error: NU1108: Cycle detected. 
error:   dumpify -> Dumpify (>= 0.6.5).
info : Package 'Dumpify' is compatible with all the specified frameworks in project 'C:\Users\USER\source\repos\dotnet\dumpify\dumpify.csproj'.
error: Value cannot be null. (Parameter 'path1')

I'm getting this error while trying to install dumpify both in vs code and in visual studio.

**Comment by MoaidHathot** [comment]
Hi @hooseinsaid, umm interesting. Could you please provide more details like what other nuget packages you have in the project? Or better yet, a minimal project/solution that reproduce this issue?
Also- as a measure of debugging in case you are using Git, could you run `git clean -fxd`? Please first commit all of your uncommitted changes.

**Comment by hooseinsaid** [comment]
thanks the issue was with that particular project I tried to recreate the issue, but it wasn't showing anymore.
