### ISSUE TITLE
Transition from MSTest to xUnit for Unit Testing

### ISSUE THREAD

**Issue by tcortega** [MoaidHathot/Dumpify#9]
Dumpify currently uses MSTest for unit testing. However, MSTest is basically an unmaintained unit testing framework. It aggregates with no actual value compared to more up-to-date and robust unit testing frameworks such as xUnit.

It'd be a strategic move that will provide long-term benefits for the project. And will ensure that it stays on top of best practices regarding to unit testing.

**Comment by MoaidHathot** [comment]
Our current testing capabilities are lacking to say the least. I was planning on investing in tests once this month's release is out, and the transition from MSTest to xUnit can be done as part of that effort
